language: generic
sudo: required
services: 
 - docker

before_install:
 - docker build -t distantgabe/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true distantgabe/react-test npm test 

after_success:
 - docker build -t distantgabe/multi-client ./client
 - docker build -t distantgabe/multi-nginx ./nginx
 - docker build -t distantgabe/multi-server ./server
 - docker build -t distantgabe/multi-worker ./worker
# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
 - docker push distantgabe/multi-client
 - docker push distantgabe/multi-nginx
 - docker push distantgabe/multi-server
 - docker push distantgabe/multi-worker

